service: import-service
frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  profile: my-profile
  stage: dev
  region: us-east-1

  environment:
    SQS_URL:
      Ref: SQSQueue

  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]

functions:
  importProductsFile:
    handler: src/functions/importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors:
            origin: '*'
          authorizer:
            arn: arn:aws:lambda:us-east-1:975555951614:function:authorization-service-dev-basicAuthorizer
            type: token
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: src/functions/importFileParser.importFileParser
    events:
      - s3:
          bucket: import-service-uploaded-csv
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded
          existing: true

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    Unauthorized:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
        ResponseType: "DEFAULT_4XX"
        RestApiId:
          Ref: "ApiGatewayRestApi"