service: import-service
frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  profile: my-profile
  stage: dev
  region: us-east-1

functions:
  importProductsFile:
    handler: src/functions/importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: src/functions/importFileParser.importFileParser
    events:
      - s3:
          bucket: import-service-uploaded-csv
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded
          existing: true